dist: trusty
sudo: false
language: python
python: "3.6"
addons:
    apt:
        sources:
            - llvm-toolchain-trusty-5.0
        packages:
            - clang-5.0

before_install:
    - pip install conan

install:
    - conan config install https://vuo.org/sites/default/files/conan-linux.zip
    - conan user

script:
    - conan create . vuo/stable ; cat /home/travis/.conan/data/patchelf/0.9/vuo/stable/build/578889a2e055243d73fcb54f389499f4b27a2016/_build/config.log
      && conan upload --remote vuo --all --confirm patchelf/*
