dist: trusty
sudo: false
language: python
python: "3.6"
addons:
    apt:
        sources:
            - llvm-toolchain-trusty-5.0
        packages:
            - clang-5.0

before_install:
    - which -a clang-5.0 ; which -a clang ; clang --version ; clang-5.0 --version ; gcc --version
    - pip install conan

install:
    - conan config install https://vuo.org/sites/default/files/conan-linux.zip
    - conan user

script:
    - conan create . vuo/stable
      && conan upload --remote vuo --all --confirm patchelf/*
